name = "sitemap-worker"
compatibility_date = "2024-05-01"
kv_namespaces = [
  { binding = "SITEMAPS", id = "your-kv-id" }
]
main = "src/worker.ts"

triggers = { crons = ["0 3 * * *"] }

# Enable module syntax
type = "module"
