name = "sitemap-worker"
main = "src/worker.ts"   # or .js if not using TypeScript
type = "module"
compatibility_date = "2024-05-01"

kv_namespaces = [
  { binding = "SITEMAPS", id = "your-kv-id" }
]

triggers = { crons = ["0 3 * * *"] }
