name: Generate and Push Sitemaps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate sitemaps
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          echo "Running sitemap generator..."
          node generate-sitemaps.js

      - name: Debug - list sitemap files
        run: |
          echo "Checking sitemap output:"
          ls -la public/sitemaps

      - name: Commit and push sitemap files
        if: success()
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public/sitemaps/* || echo "No files to add"
          git commit -m "Update sitemaps [CI]" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }} || echo "Nothing to push"
