name: Generate and Push Sitemaps

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Print current directory & list files before generation
        run: |
          pwd
          ls -la
          ls -la public || echo "No public directory"
          ls -la public/sitemaps || echo "No sitemap directory yet"

      - name: Generate sitemaps
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: |
          echo "Running sitemap generator..."
          node generate-sitemaps.js

      - name: List sitemap files after generation
        run: ls -la public/sitemaps || echo "No sitemap files found"

      - name: Show git status and staged files before add
        run: |
          git status
          git diff --name-only
          git diff --cached --name-only || echo "No files staged yet"

      - name: Add sitemap files to git
        run: git add public/sitemaps/*

      - name: Show git status and staged files after add
        run: |
          git status
          git diff --cached --name-only

      - name: Commit sitemap files
        run: |
          git commit -m "Update sitemaps [CI]" || echo "No changes to commit"

      - name: Show git log last 3 commits
        run: git log -3 --oneline

      - name: Push changes to main branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main || echo "Nothing to push"
